Add crashlog instructions for non-vanilla launchers
Polyfrost/PolyHelper pull request #18
Opened 2024-06-08 11:16 UTC by KTrain5169

Would it just be better to put a GitHub Gist with instructions or smth?
(Obviously vanilla launcher steps would still be using KTibow's video)

2024-06-08 17:16 UTC, RuiNtD commented on src/interaction-handlers/ticket/categorizeCrash.ts
> +1. Open your SkyClient folder. If you use the vanilla launcher, see this: https://youtu.be/BHIM2htfMk8
New users probably won't know what "vanilla launcher" is. "Minecraft Launcher" is probably preferred here.
```suggestion
1. Open your SkyClient folder. If you use Minecraft Launcher, see this: https://youtu.be/BHIM2htfMk8
```

2024-06-08 17:16 UTC, RuiNtD commented on src/interaction-handlers/ticket/categorizeCrash.ts
> +   - **If you use Prism, Modrinth (app) or another non-vanilla launcher:***
We only "officially" support Prism and Modrinth. This is probably better phrasing:
```suggestion
   - **If you use the Prism or Modrinth Launcher:***
```

2024-06-08 17:16 UTC, RuiNtD commented on src/interaction-handlers/ticket/categorizeCrash.ts
> +     Then, upload the \`fml-client-latest\` file into the channel.
```suggestion
     Then upload the \`fml-client-latest\` file here.
```

2024-06-09 03:39 UTC, RuiNtD approved these changes

2024-06-15 15:54 UTC, RuiNtD requested changes
Too wordy. What was there before was sufficient.

2024-06-17 07:45 UTC, RuinTD approved these changes

2024-06-25 04:22 UTC, RuiNtD commented
I'm going to refine this in main branch.

2024-06-25 09:40 UTC, KTrain5169 commented
No longer necessary with the new code in place. Will probably open another PR to refine instructions there.

2024-06-25 09:40 UTC, closed without merging